# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise32"
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :public_network, ip: "192.168.33.11"
  config.vm.synced_folder "~/www/viladasmerces", "/srv/www/viladasmerces" 
  
  config.vm.define :viladasmerces do |t|
  end

  Vagrant::Config.run do |config|
    config.vm.customize ["modifyvm", :id, "--memory", 1024]
  end
end
